# Start vault server locally for the purposes of integration tests.
version: "3.0"
services:
  vault:
    image: vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testtoken
    ports:
      - 8200:8200
    privileged: true
  vault-enterprise:
    image: hashicorp/vault-enterprise:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testtoken
      VAULT_LICENSE: ${VAULT_LICENSE_CI}
    ports:
      - 8200:8200
    privileged: true
  vault-tls:
    image: vault:latest
    hostname: vault-tls
    environment:
      VAULT_CAPATH: /etc/vault/ca.crt
    ports:
    - 8200:8200
    privileged: true
    volumes:
    - ${PWD}/integrationTests/e2e-tls/configs:/etc/vault
    - vault-data:/var/lib/vault:rw
    entrypoint: vault server -config=/etc/vault/config.hcl

volumes:
  vault-data:
